- name: Set home dir path facts
  ansible.builtin.set_fact:
    xdg_base_dirs__cache_dir_path: /home/{{ ansible_user }}/.cache
    xdg_base_dirs__config_dir_path: /home/{{ ansible_user }}/.config
    xdg_base_dirs__data_dir_path: /home/{{ ansible_user }}/.local/share
    xdg_base_dirs__exe_dir_path: /home/{{ ansible_user }}/.local/bin
    xdg_base_dirs__state_dir_path: /home/{{ ansible_user }}/.local/state

- name: Set home dir path facts for root
  ansible.builtin.set_fact:
    xdg_base_dirs__root_cache_dir_path: /root/.cache
    xdg_base_dirs__root_config_dir_path: /root/.config
    xdg_base_dirs__root_data_dir_path: /root/.local/share
    xdg_base_dirs__root_exe_dir_path: /root/.local/bin
    xdg_base_dirs__root_state_dir_path: /root/.local/state

- name: Create home dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=,o=
  loop:
    - "{{ xdg_base_dirs__cache_dir_path }}"
    - "{{ xdg_base_dirs__config_dir_path }}"
    - "{{ xdg_base_dirs__data_dir_path }}"
    - "{{ xdg_base_dirs__exe_dir_path }}"
    - "{{ xdg_base_dirs__state_dir_path }}"

- name: Create home dirs for root
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=,o=
  become: true
  loop:
    - "{{ xdg_base_dirs__root_cache_dir_path }}"
    - "{{ xdg_base_dirs__root_config_dir_path }}"
    - "{{ xdg_base_dirs__root_data_dir_path }}"
    - "{{ xdg_base_dirs__root_exe_dir_path }}"
    - "{{ xdg_base_dirs__root_state_dir_path }}"
