- name: Set home dir path facts
  ansible.builtin.set_fact:
    xdg_cache_home_dir_path: /home/{{ ansible_user }}/.cache
    xdg_config_home_dir_path: /home/{{ ansible_user }}/.config
    xdg_data_home_dir_path: /home/{{ ansible_user }}/.local/share
    xdg_exe_home_dir_path: /home/{{ ansible_user }}/.local/bin
    xdg_state_home_dir_path: /home/{{ ansible_user }}/.local/state

- name: Set custom dir path facts
  ansible.builtin.set_fact:
    opt_provider_dir_path: /opt/{{ ansible_user }}

- name: Create home dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=,o=
  loop:
    - "{{ xdg_cache_home_dir_path }}"
    - "{{ xdg_config_home_dir_path }}"
    - "{{ xdg_data_home_dir_path }}"
    - "{{ xdg_exe_home_dir_path }}"
    - "{{ xdg_state_home_dir_path }}"

- name: Create custom dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
  become: true
  loop:
    - "{{ opt_provider_dir_path }}"
