- name: Set data dir path fact
  ansible.builtin.set_fact:
    systemd_failure_data_dir: >-
      {{ xdg_data_home_dir_path }}/systemd-failure

- name: Set misc facts
  ansible.builtin.set_fact:
    systemd_failure_unit_name: handle-systemd-failure.service
    systemd_failure_script_path: >-
      {{ systemd_failure_data_dir }}/handle-systemd-failure.sh

- name: Create dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ systemd_failure_data_dir }}"

- name: Render and place script
  ansible.builtin.template:
    src: handle-systemd-failure.sh
    dest: "{{ systemd_failure_script_path }}"
    mode: u=rwx,g=,o=
  register: systemd_failure_script

- name: Symlink script
  ansible.builtin.file:
    src: "{{ systemd_failure_script_path }}"
    dest: $HOME/.local/bin/handle-systemd-failure
    state: link

- name: Set up systemd unit unit-failure-handle@.service
  ansible.builtin.include_role:
    name: trallnag.systemd_unit
  vars:
    systemd_unit_name: unit-failure-handle@.service
    systemd_unit_activate: false
    systemd_unit_running_check: false
    systemd_unit_restart: "{{ systemd_failure_script.changed }}"
    systemd_unit_content: >-
      {{
        lookup(
          "ansible.builtin.template",
          "unit-failure-handle@.service"
        )
      }}
