- name: Set config dir path fact
  ansible.builtin.set_fact:
    shell_config_dir_path: "{{ xdg_config_home_dir_path }}/shell"

- name: Set config dir path fact for root
  ansible.builtin.set_fact:
    shell_root_config_dir_path: "{{ xdg_root_config_home_dir_path }}/shell"

- name: Set login script path facts
  ansible.builtin.set_fact:
    shell_bash_login_script_path: "{{ shell_config_dir_path }}/login.bash"
    shell_fish_login_script_path: "{{ shell_config_dir_path }}/login.fish"
    shell_zsh_login_script_path: "{{ shell_config_dir_path }}/login.zsh"

- name: Set login script path facts for root
  ansible.builtin.set_fact:
    shell_root_bash_login_script_path: "{{ shell_root_config_dir_path }}/login.bash"
    shell_root_fish_login_script_path: "{{ shell_root_config_dir_path }}/login.fish"
    shell_root_zsh_login_script_path: "{{ shell_root_config_dir_path }}/login.zsh"

- name: Create config dir
  ansible.builtin.file:
    path: "{{ shell_config_dir_path }}"
    state: directory
    mode: u=rwx,g=,o=

- name: Create config dir for root
  ansible.builtin.file:
    path: "{{ shell_root_config_dir_path }}"
    state: directory
    mode: u=rwx,g=,o=
  become: true

- name: Create login scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: u=rw,g=,o=
    modification_time: preserve
    access_time: preserve
  loop:
    - "{{ shell_bash_login_script_path }}"
    - "{{ shell_fish_login_script_path }}"
    - "{{ shell_zsh_login_script_path }}"

- name: Create login scripts for root
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: u=rw,g=,o=
    modification_time: preserve
    access_time: preserve
  become: true
  loop:
    - "{{ shell_root_bash_login_script_path }}"
    - "{{ shell_root_fish_login_script_path }}"
    - "{{ shell_root_zsh_login_script_path }}"

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ shell_bash_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    insertbefore: BOF
    block: "{{ lookup('ansible.builtin.template', 'login.bash') }}"

- name: Set up environment in Bash for root
  ansible.builtin.blockinfile:
    path: "{{ shell_root_bash_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    insertbefore: BOF
    block: >-
      {{
        lookup('ansible.builtin.template', 'login.bash', template_vars={
          'xdg_cache_home_dir_path': xdg_root_cache_home_dir_path,
          'xdg_config_home_dir_path': xdg_root_config_home_dir_path,
          'xdg_data_home_dir_path': xdg_root_data_home_dir_path,
          'xdg_exe_home_dir_path': xdg_root_exe_home_dir_path,
          'xdg_state_home_dir_path': xdg_root_state_home_dir_path,
          'shell_bash_login_script_path': shell_root_bash_login_script_path,
          'shell_fish_login_script_path': shell_root_fish_login_script_path,
          'shell_zsh_login_script_path': shell_root_zsh_login_script_path,
        })
      }}
  become: true

- name: Set up environment in Fish
  ansible.builtin.blockinfile:
    path: "{{ shell_fish_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    insertbefore: BOF
    block: "{{ lookup('ansible.builtin.template', 'login.fish') }}"

- name: Set up environment in Fish for root
  ansible.builtin.blockinfile:
    path: "{{ shell_root_fish_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    insertbefore: BOF
    block: >-
      {{
        lookup('ansible.builtin.template', 'login.fish', template_vars={
          'xdg_cache_home_dir_path': xdg_root_cache_home_dir_path,
          'xdg_config_home_dir_path': xdg_root_config_home_dir_path,
          'xdg_data_home_dir_path': xdg_root_data_home_dir_path,
          'xdg_exe_home_dir_path': xdg_root_exe_home_dir_path,
          'xdg_state_home_dir_path': xdg_root_state_home_dir_path,
          'shell_bash_login_script_path': shell_root_bash_login_script_path,
          'shell_fish_login_script_path': shell_root_fish_login_script_path,
          'shell_zsh_login_script_path': shell_root_zsh_login_script_path,
        })
      }}
  become: true

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ shell_zsh_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    insertbefore: BOF
    block: "{{ lookup('ansible.builtin.template', 'login.zsh') }}"

- name: Set up environment in Zsh for root
  ansible.builtin.blockinfile:
    path: "{{ shell_root_zsh_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    insertbefore: BOF
    block: >-
      {{
        lookup('ansible.builtin.template', 'login.zsh', template_vars={
          'xdg_cache_home_dir_path': xdg_root_cache_home_dir_path,
          'xdg_config_home_dir_path': xdg_root_config_home_dir_path,
          'xdg_data_home_dir_path': xdg_root_data_home_dir_path,
          'xdg_exe_home_dir_path': xdg_root_exe_home_dir_path,
          'xdg_state_home_dir_path': xdg_root_state_home_dir_path,
          'shell_bash_login_script_path': shell_root_bash_login_script_path,
          'shell_fish_login_script_path': shell_root_fish_login_script_path,
          'shell_zsh_login_script_path': shell_root_zsh_login_script_path,
        })
      }}
  become: true
