- name: Install formulae (present)
  community.general.homebrew:
    name:
      - gh
      - helm
      - hugo
      - kubectx
      - zellij
    state: present

- name: Install formulae (unlinked)
  community.general.homebrew:
    name:
      - kubernetes-cli
    state: unlinked
