- name: Install formulae (present)
  community.general.homebrew:
    name:
      - gh
      - helm
      - hugo
      - kubectx
      - zellij
    state: present

- name: Add formulae to unlink file
  ansible.builtin.lineinfile:
    path: "{{ homebrew_unliked }}"
    line: "{{ item }}"
  with_items:
    - kubernetes-cli
