- name: Set data dir path fact
  ansible.builtin.set_fact:
    homebrew_data_dir_path: /home/linuxbrew/.linuxbrew

- name: Set exe dir path fact
  ansible.builtin.set_fact:
    homebrew_exe_dir_path: "{{ homebrew_data_dir_path }}/bin"

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - file
      - git
      - procps
  become: true

- name: Install
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: "{{ lookup('ansible.builtin.template', 'install.sh') }}"
  register: homebrew_install
  changed_when: "'status=changed' in homebrew_install.stdout"

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ bash__profile_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      eval "$({{ homebrew_exe_dir_path }}/brew shellenv)"
      export HOMEBREW_PREFIX="{{ homebrew_data_dir_path }}"
      export HOMEBREW_GITHUB_API_TOKEN="{{ github_scopeless_token }}"

- name: Set up completion in Bash
  ansible.builtin.blockinfile:
    path: "{{ bash__bashrc_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} completion"
    block: |
      source "{{ homebrew_data_dir_path }}/etc/bash_completion.d/"*

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh__zprofile_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      eval "$({{ homebrew_exe_dir_path }}/brew shellenv)"
      export HOMEBREW_PREFIX="{{ homebrew_data_dir_path }}"
      export HOMEBREW_GITHUB_API_TOKEN="{{ github_scopeless_token }}"

- name: Set up completion in Zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh__zshrc_compinit_pre_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} completion"
    block: |
      FPATH="{{ homebrew_data_dir_path }}/share/zsh/site-functions:$FPATH"
