- name: Install
  community.general.homebrew:
    name: ripgrep
    path: "{{ homebrew_exe_dir_path }}"

- name: Set config dir path fact
  ansible.builtin.set_fact:
    ripgrep_config_dir_path: "{{ base_dirs_xdg__config_dir_path }}/ripgrep"

- name: Set config path fact
  ansible.builtin.set_fact:
    ripgrep_config_path: "{{ ripgrep_config_dir_path }}/ripgrep.conf"

- name: Create config dir
  ansible.builtin.file:
    state: directory
    path: "{{ ripgrep_config_dir_path }}"
    mode: u=rwx,g=,o=

- name: Place config file
  ansible.builtin.copy:
    src: ripgrep.conf
    dest: "{{ ripgrep_config_path }}"
    mode: u=rw,g=,o=

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ bash__profile_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export RIPGREP_CONFIG_PATH="{{ ripgrep_config_path }}"

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh__zprofile_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export RIPGREP_CONFIG_PATH="{{ ripgrep_config_path }}"
