- name: Install
  community.general.homebrew:
    name: tenv
    path: "{{ homebrew_exe_dir_path }}"

- name: Set exe path fact
  ansible.builtin.set_fact:
    tenv_exe_path: "{{ homebrew_exe_dir_path }}/tenv"

- name: Set data dir path fact
  ansible.builtin.set_fact:
    tenv_data_dir_path: "{{ xdg_base_dirs__data_dir_path }}/tenv"

- name: Create data dir
  ansible.builtin.file:
    state: directory
    path: "{{ tenv_data_dir_path }}"
    mode: u=rwx,g=,o=

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ shell__bash_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export TENV_ROOT="{{ tenv_data_dir_path }}"
      export TENV_AUTO_INSTALL="true"

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ shell__zsh_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export TENV_ROOT="{{ tenv_data_dir_path }}"
      export TENV_AUTO_INSTALL="true"
