- name: Install
  community.general.homebrew:
    name: bat
    path: "{{ homebrew_exe_dir_path }}"

- name: Set config dir path fact
  ansible.builtin.set_fact:
    bat_config_dir_path: "{{ base_dirs_xdg__config_dir_path }}/bat"

- name: Set config path fact
  ansible.builtin.set_fact:
    bat_config_path: "{{ bat_config_dir_path }}/bat.conf"

- name: Create config dir
  ansible.builtin.file:
    state: directory
    path: "{{ bat_config_dir_path }}"
    mode: u=rwx,g=,o=

- name: Place config file
  ansible.builtin.copy:
    src: bat.conf
    dest: "{{ bat_config_path }}"
    mode: u=rw,g=,o=

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ shell__bash_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export BAT_CONFIG_PATH="{{ bat_config_path }}"

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ shell__zsh_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export BAT_CONFIG_PATH="{{ bat_config_path }}"
