- name: Set dir path facts
  ansible.builtin.set_fact:
    windows_burnt_toast__data_dir_path:  >-
      {{ fhs_base_dirs__opt_data_dir_path }}/windows-burnt-toast

    windows_burnt_toast__win_data_dir_path: >-
      {{ windows_home_dir_path }}/Share/BurntToast
    windows_burnt_toast__win_data_dir_win_path: >-
      {{ windows_home_dir_win_path }}\Share\BurntToast

- name: Set misc facts
  ansible.builtin.set_fact:
    windows_burnt_toast__send_burnt_toast_exe_path: >-
      {{ fhs_base_dirs__opt_exe_dir_path }}/send-burnt-toast

    windows_burnt_toast__icon_path: >-
      {{ windows_burnt_toast__win_data_dir_path }}/toast-icon.png
    windows_burnt_toast__icon_win_path: >-
      {{ windows_burnt_toast__win_data_dir_win_path }}\toast-icon.png

- name: Create dir
  ansible.builtin.file:
    path: "{{ windows_burnt_toast__data_dir_path }}"
    state: directory
  become: true

- name: Create win dir
  ansible.builtin.file:
    path: "{{ windows_burnt_toast__win_data_dir_path }}"
    state: directory

- name: Place toast icon
  ansible.builtin.copy:
    src: toast-icon.png
    dest: "{{ windows_burnt_toast__icon_path }}"

- name: Render and place script
  ansible.builtin.template:
    src: send-burnt-toast.sh
    dest: "{{ windows_burnt_toast__data_dir_path }}/send-burnt-toast.sh"
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Symlink script
  ansible.builtin.file:
    src: "{{ windows_burnt_toast__data_dir_path }}/send-burnt-toast.sh"
    dest: "{{ windows_burnt_toast__send_burnt_toast_exe_path }}"
    state: link
  become: true

- name: Install module
  ansible.builtin.command:
    cmd: >-
      pwsh.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File
      "{{ role_path }}/files/install-module.ps1"
      -IconPath "{{ windows_burnt_toast__icon_win_path }}"
  register: this
  changed_when: "'status=changed' in this.stdout"

- name: Register app
  ansible.builtin.command:
    cmd: >-
      pwsh.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File
      "{{ role_path }}/files/register-app.ps1"
      -IconPath "{{ windows_burnt_toast__icon_win_path }}"
  changed_when: false
