- name: Install
  community.general.homebrew:
    name: eza
    path: "{{ homebrew_exe_dir_path }}"

- name: Set config dir path fact
  ansible.builtin.set_fact:
    eza_config_dir_path: "{{ base_dirs_xdg__config_dir_path }}/eza"

- name: Create config dir
  ansible.builtin.file:
    state: directory
    path: "{{ eza_config_dir_path }}"
    mode: u=rwx,g=,o=

- name: Place theme config
  ansible.builtin.copy:
    src: theme.yml
    dest: "{{ eza_config_dir_path }}/theme.yml"
    mode: u=rw,g=,o=

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ shell__bash_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export EZA_CONFIG_DIR="{{ eza_config_dir_path }}"

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ shell__zsh_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export EZA_CONFIG_DIR="{{ eza_config_dir_path }}"

- name: Set aliases fact
  ansible.builtin.set_fact:
    eza_aliases:
      - word: eo
        subst: >-
          eza
          --all
          --group-directories-first
          --icons=auto
          --oneline
      - word: el
        subst: >-
          eza
          --all
          --classify
          --git
          --git-repos
          --group-directories-first
          --header
          --icons=auto
          --long
          --mounts
          --no-time
          --time-style=long-iso
      - word: ll
        subst: >-
          eza
          --all
          --classify
          --git
          --git-repos
          --group-directories-first
          --header
          --icons=auto
          --long
          --mounts
          --no-time
          --time-style=long-iso
      - word: ex
        subst: >-
          eza
          --accessed
          --all
          --binary
          --blocksize
          --created
          --extended
          --git
          --git-repos
          --group
          --group-directories-first
          --header
          --icons=auto
          --inode
          --links
          --long
          --modified
          --mounts
          --time-style=long-iso
      - word: et
        subst: >-
          eza
          --all
          --group-directories-first
          --tree

- name: Set up aliases in bash
  ansible.builtin.blockinfile:
    path: "{{ bash__aliases_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }}"
    block: |
      {% for alias in eza_aliases %}
      alias {{ alias.word }}='{{ alias.subst }}'
      {% endfor %}

- name: Set up aliases in zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh__aliases_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }}"
    block: |
      {% for alias in eza_aliases %}
      alias {{ alias.word }}='{{ alias.subst }}'
      {% endfor %}
