- name: Import role trallnag.aws_cli
  ansible.builtin.import_role:
    name: trallnag.aws_cli
  vars:
    aws_cli__version: latest

- name: Import role trallnag.aws_ssm_plugin
  ansible.builtin.import_role:
    name: trallnag.aws_ssm_plugin
  vars:
    aws_ssm_plugin__version: latest

- name: Import role trallnag.aws_sam_cli
  ansible.builtin.import_role:
    name: trallnag.aws_sam_cli
  vars:
    aws_sam_cli__version: latest

- name: Set up completion in Bash
  ansible.builtin.blockinfile:
    path: "{{ bash__bashrc_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} completion"
    block: |
      complete -C /usr/local/bin/aws_completer aws

- name: Set up completion in Bash for root
  ansible.builtin.blockinfile:
    path: "{{ bash__root_bashrc_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} completion"
    block: |
      complete -C /usr/local/bin/aws_completer aws
  become: true

- name: Set up completion in Zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh__zshrc_compinit_post_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} completion"
    block: |
      complete -C /usr/local/bin/aws_completer aws

- name: Set up completion in Zsh for root
  ansible.builtin.blockinfile:
    path: "{{ zsh__root_zshrc_compinit_post_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} completion"
    block: |
      complete -C /usr/local/bin/aws_completer aws
  become: true
