- name: Install
  community.general.homebrew:
    name:
      - age # https://github.com/FiloSottile/age
      - cosign # https://github.com/sigstore/cosign
      - fd # https://github.com/sharkdp/fd
      - gh # https://github.com/cli/cli
      - go-task # https://taskfile.dev
      - helm # https://helm.sh/
      - just # https://github.com/casey/just
      - kubectx # https://github.com/ahmetb/kubectx
      - kubernetes-cli # https://kubernetes.io/docs/reference/kubectl/
      - optipng # http://optipng.sourceforge.net
      - shellcheck # https://github.com/koalaman/shellcheck
      - shfmt # https://github.com/mvdan/sh
      - watchexec # https://github.com/watchexec/watchexec
      - zellij # https://github.com/zellij-org/zellij
    path: "{{ homebrew_exe_dir_path }}"
