typeset -g POWERLEVEL9K_CONTEXT_PREFIX=

typeset -g POWERLEVEL9K_HOME_ICON=
typeset -g POWERLEVEL9K_HOME_SUB_ICON=
typeset -g POWERLEVEL9K_FOLDER_ICON=

typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=

typeset -g POWERLEVEL9K_ANACONDA_PREFIX='%fin '
typeset -g POWERLEVEL9K_ANACONDA_VISUAL_IDENTIFIER_EXPANSION=''

typeset -g POWERLEVEL9K_VIRTUALENV_PREFIX='%fin '
typeset -g POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION='󰌠'

typeset -g POWERLEVEL9K_TOP_LEFT_PROMPT_ELEMENTS=(
  context
  dir
  vcs
  status
  command_execution_time
  background_jobs
  virtualenv
  anaconda
  kubecontext
)

typeset -g POWERLEVEL9K_BOTTOM_LEFT_PROMPT_ELEMENTS=(
  prompt_char
)

typeset -g POWERLEVEL9K_TOP_RIGHT_PROMPT_ELEMENTS=()

typeset -g POWERLEVEL9K_BOTTOM_RIGHT_PROMPT_ELEMENTS=()
