typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  $POWERLEVEL9K_TOP_LEFT_PROMPT_ELEMENTS
  newline
  $POWERLEVEL9K_BOTTOM_LEFT_PROMPT_ELEMENTS
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  $POWERLEVEL9K_TOP_RIGHT_PROMPT_ELEMENTS
  newline
  $POWERLEVEL9K_BOTTOM_RIGHT_PROMPT_ELEMENTS
)
