- name: Install with asdf
  ansible.builtin.import_role:
    name: trallnag.asdf_plugin
  vars:
    asdf_plugin_name: kubens
    asdf_plugin_git_url: https://github.com/trallnag/asdf-kubens.git
    asdf_plugin_package_versions: ["{{ kubens_version }}"]
    asdf_plugin_package_version_global: "{{ kubens_version }}"

- name: "bash : Download completion script and place it"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectx/v{{ kubens_version }}/completion/kubens.bash
    dest: "{{ bash_completions }}/kubens.bash"
    force: true

- name: "zsh : Download completion script and place it"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectx/v{{ kubens_version }}/completion/kubens.zsh
    dest: "{{ zsh_completions }}/_kubens"
    force: true
