- name: Set config dir path fact
  ansible.builtin.set_fact:
    git_config_dir_path: "{{ base_dirs_xdg__config_dir_path }}/git"

- name: Set config path facts
  ansible.builtin.set_fact:
    git_config_path: "{{ git_config_dir_path }}/config"
    git_managed_config_path: "{{ git_config_dir_path }}/managed_config"

- name: Create config dir
  ansible.builtin.file:
    state: directory
    path: "{{ git_config_dir_path }}"
    mode: u=rwx,g=,o=

- name: Touch config file
  ansible.builtin.file:
    path: "{{ git_config_path }}"
    state: touch
    mode: u=rw,g=,o=
    modification_time: preserve
    access_time: preserve

- name: Include managed config file
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      set -euo pipefail

      hash_before=$(sha256sum "{{ git_config_path }}")

      git="git config --file {{ git_config_path }}"

      $git include.path "{{ git_managed_config_path }}"

      hash_after=$(sha256sum "{{ git_config_path }}")

      if [ "$hash_before" != "$hash_after" ]; then
        echo status=changed
      fi
  register: this
  changed_when: "'status=changed' in this.stdout"

- name: Place managed config file
  ansible.builtin.copy:
    src: "{{ git_managed_config_path | basename }}"
    dest: "{{ git_managed_config_path }}"
    mode: u=rw,g=,o=
