- name: Set dir path facts
  ansible.builtin.set_fact:
    bash_config_dir_path: "{{ xdg_config_home_dir_path }}/bash"
    bash_completions_dir_path: "{{ xdg_data_home_dir_path }}/bash-completion/completions"

- name: Set dir path facts for root
  ansible.builtin.set_fact:
    bash_root_config_dir_path: "{{ xdg_root_config_home_dir_path }}/bash"
    bash_root_completions_dir_path: "{{ xdg_root_data_home_dir_path }}/bash-completion/completions"

- name: Set script path facts
  ansible.builtin.set_fact:
    bash_completion_script_path: "{{ xdg_config_home_dir_path }}/bash_completion"
    bash_profile_script_path: "{{ bash_config_dir_path }}/profile.bash"
    bash_bashrc_top_script_path: "{{ bash_config_dir_path }}/bashrc-top.bash"
    bash_bashrc_script_path: "{{ bash_config_dir_path }}/bashrc.bash"
    bash_aliases_script_path: "{{ bash_config_dir_path }}/aliases.bash"

- name: Set script path facts for root
  ansible.builtin.set_fact:
    bash_root_completion_script_path: "{{ xdg_root_config_home_dir_path }}/bash_completion"
    bash_root_profile_script_path: "{{ bash_root_config_dir_path }}/profile.bash"
    bash_root_bashrc_top_script_path: "{{ bash_root_config_dir_path }}/bashrc-top.bash"
    bash_root_bashrc_script_path: "{{ bash_root_config_dir_path }}/bashrc.bash"
    bash_root_aliases_script_path: "{{ bash_root_config_dir_path }}/aliases.bash"

- name: Create dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=,o=
  loop:
    - "{{ bash_config_dir_path }}"
    - "{{ bash_completions_dir_path }}"

- name: Create dirs for root
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=,o=
  become: true
  loop:
    - "{{ bash_root_config_dir_path }}"
    - "{{ bash_root_completions_dir_path }}"

- name: Create scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: u=rw,g=,o=
    modification_time: preserve
    access_time: preserve
  loop:
    - "{{ bash_completion_script_path }}"
    - "{{ bash_profile_script_path }}"
    - "{{ bash_bashrc_top_script_path }}"
    - "{{ bash_bashrc_script_path }}"
    - "{{ bash_aliases_script_path }}"

- name: Create scripts for root
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: u=rw,g=,o=
    modification_time: preserve
    access_time: preserve
  become: true
  loop:
    - "{{ bash_root_completion_script_path }}"
    - "{{ bash_root_profile_script_path }}"
    - "{{ bash_root_bashrc_top_script_path }}"
    - "{{ bash_root_bashrc_script_path }}"
    - "{{ bash_root_aliases_script_path }}"

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ shell_bash_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export DOT_BASH_CONFIG_DIR_PATH="{{ bash_config_dir_path }}"
      export DOT_BASH_COMPLETIONS_DIR_PATH="{{ bash_completions_dir_path }}"
      export DOT_BASH_COMPLETION_SCRIPT_PATH="{{ bash_completion_script_path }}"
      export DOT_BASH_PROFILE_SCRIPT_PATH="{{ bash_profile_script_path }}"
      export DOT_BASH_BASHRC_TOP_SCRIPT_PATH="{{ bash_bashrc_top_script_path }}"
      export DOT_BASH_BASHRC_SCRIPT_PATH="{{ bash_bashrc_script_path }}"
      export DOT_BASH_ALIASES_SCRIPT_PATH="{{ bash_aliases_script_path }}"

- name: Set up environment in Bash for root
  ansible.builtin.blockinfile:
    path: "{{ shell_root_bash_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export DOT_BASH_CONFIG_DIR_PATH="{{ bash_root_config_dir_path }}"
      export DOT_BASH_COMPLETIONS_DIR_PATH="{{ bash_root_completions_dir_path }}"
      export DOT_BASH_COMPLETION_SCRIPT_PATH="{{ bash_root_completion_script_path }}"
      export DOT_BASH_PROFILE_SCRIPT_PATH="{{ bash_root_profile_script_path }}"
      export DOT_BASH_BASHRC_TOP_SCRIPT_PATH="{{ bash_root_bashrc_top_script_path }}"
      export DOT_BASH_BASHRC_SCRIPT_PATH="{{ bash_root_bashrc_script_path }}"
      export DOT_BASH_ALIASES_SCRIPT_PATH="{{ bash_root_aliases_script_path }}"
  become: true

- name: Set up environment in Fish
  ansible.builtin.blockinfile:
    path: "{{ shell_fish_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      set -x DOT_BASH_CONFIG_DIR_PATH "{{ bash_config_dir_path }}"
      set -x DOT_BASH_COMPLETIONS_DIR_PATH "{{ bash_completions_dir_path }}"
      set -x DOT_BASH_COMPLETION_SCRIPT_PATH "{{ bash_completion_script_path }}"
      set -x DOT_BASH_PROFILE_SCRIPT_PATH "{{ bash_profile_script_path }}"
      set -x DOT_BASH_BASHRC_TOP_SCRIPT_PATH "{{ bash_bashrc_top_script_path }}"
      set -x DOT_BASH_BASHRC_SCRIPT_PATH "{{ bash_bashrc_script_path }}"
      set -x DOT_BASH_ALIASES_SCRIPT_PATH "{{ bash_aliases_script_path }}"

- name: Set up environment in Fish for root
  ansible.builtin.blockinfile:
    path: "{{ shell_root_fish_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      set -x DOT_BASH_CONFIG_DIR_PATH "{{ bash_root_config_dir_path }}"
      set -x DOT_BASH_COMPLETIONS_DIR_PATH "{{ bash_root_completions_dir_path }}"
      set -x DOT_BASH_COMPLETION_SCRIPT_PATH "{{ bash_root_completion_script_path }}"
      set -x DOT_BASH_PROFILE_SCRIPT_PATH "{{ bash_root_profile_script_path }}"
      set -x DOT_BASH_BASHRC_TOP_SCRIPT_PATH "{{ bash_root_bashrc_top_script_path }}"
      set -x DOT_BASH_BASHRC_SCRIPT_PATH "{{ bash_root_bashrc_script_path }}"
      set -x DOT_BASH_ALIASES_SCRIPT_PATH "{{ bash_root_aliases_script_path }}"
  become: true

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ shell_zsh_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export DOT_BASH_CONFIG_DIR_PATH="{{ bash_config_dir_path }}"
      export DOT_BASH_COMPLETIONS_DIR_PATH="{{ bash_completions_dir_path }}"
      export DOT_BASH_COMPLETION_SCRIPT_PATH="{{ bash_completion_script_path }}"
      export DOT_BASH_PROFILE_SCRIPT_PATH="{{ bash_profile_script_path }}"
      export DOT_BASH_BASHRC_TOP_SCRIPT_PATH="{{ bash_bashrc_top_script_path }}"
      export DOT_BASH_BASHRC_SCRIPT_PATH="{{ bash_bashrc_script_path }}"
      export DOT_BASH_ALIASES_SCRIPT_PATH="{{ bash_aliases_script_path }}"

- name: Set up environment in Zsh for root
  ansible.builtin.blockinfile:
    path: "{{ shell_root_zsh_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export DOT_BASH_CONFIG_DIR_PATH="{{ bash_root_config_dir_path }}"
      export DOT_BASH_COMPLETIONS_DIR_PATH="{{ bash_root_completions_dir_path }}"
      export DOT_BASH_COMPLETION_SCRIPT_PATH="{{ bash_root_completion_script_path }}"
      export DOT_BASH_PROFILE_SCRIPT_PATH="{{ bash_root_profile_script_path }}"
      export DOT_BASH_BASHRC_TOP_SCRIPT_PATH="{{ bash_root_bashrc_top_script_path }}"
      export DOT_BASH_BASHRC_SCRIPT_PATH="{{ bash_root_bashrc_script_path }}"
      export DOT_BASH_ALIASES_SCRIPT_PATH="{{ bash_root_aliases_script_path }}"
  become: true

- name: Delete .bash_profile from home
  ansible.builtin.file:
    path: $HOME/.bash_profile
    state: absent

- name: Delete .bash_profile from home for root
  ansible.builtin.file:
    path: /root/.bash_profile
    state: absent
  become: true

- name: Place files in home
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "$HOME/{{ item }}"
    mode: u=rw,g=,o=
  loop:
    - .bashrc
    - .bash_logout

- name: Place files in home for root
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
    mode: u=rw,g=,o=
  become: true
  loop:
    - .bashrc
    - .bash_logout

- name: Render and place files in home
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "$HOME/{{ item }}"
    mode: u=rw,g=,o=
  vars:
    _shell_bash_login_script_path: "{{ shell_bash_login_script_path }}"
  loop:
    - .profile

- name: Render and place files in home for root
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
    mode: u=rw,g=,o=
  become: true
  vars:
    _shell_bash_login_script_path: "{{ shell_root_bash_login_script_path }}"
  loop:
    - .profile
