- name: Install
  community.general.homebrew:
    name: git-extras
    state: present

# Necessary due to caveat in formula. For some reason completion for Zsh is
# not being setup automatically. For Bash it works fine out of the box.
- name: 'zsh : Add completion block to zsh_zshrc_bottom_after_comp_init'
  blockinfile:
    path: '{{ zsh_zshrc_bottom_after_comp_init }}'
    marker: '# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}'
    block: |
      file=/home/linuxbrew/.linuxbrew/opt/git-extras/share/git-extras/git-extras-completion.zsh
      test -f $file && source $file
