- name: Set data dir path fact
  ansible.builtin.set_fact:
    windows_gpg_agent_relay_data_dir_path: >-
      {{ xdg_data_home_dir_path }}/windows-gpg-agent-relay

- name: Set miscellaneous facts
  ansible.builtin.set_fact:
    windows_gpg_agent_relay_unit_name: windows-gpg-agent-relay.service

    windows_gpg_agent_relay_script_path: >-
      {{ windows_gpg_agent_relay_data_dir_path }}/windows-gpg-agent-relay.sh

    # Path to the OpenSSH executable in Windows. Must be the special Windows
    # fork of OpenSSH that stores keys within a Windows security context.
    windows_gpg_agent_relay_ssh_exe_path: >-
      {{ windows_mount_dir_path }}/Windows/System32/OpenSSH/ssh.exe

- name: Check executable existence
  ansible.builtin.stat:
    path: "{{ windows_gpg_agent_relay_ssh_exe_path }}"

- name: Check executable usability
  ansible.builtin.command:
    cmd: "'{{ windows_gpg_agent_relay_ssh_exe_path }}' -V"
  changed_when: false

- name: Create data dir
  ansible.builtin.file:
    state: directory
    path: "{{ windows_gpg_agent_relay_data_dir_path }}"
    mode: u=rwx,g=,o=

- name: Render and place script
  ansible.builtin.template:
    src: "{{ windows_gpg_agent_relay_script_path | basename }}"
    dest: "{{ windows_gpg_agent_relay_script_path }}"
    mode: u=rwx,g=,o=
  register: windows_gpg_agent_relay_script

- name: Set up systemd unit
  ansible.builtin.include_role:
    name: trallnag.systemd_unit
  vars:
    systemd_unit_name: "{{ windows_gpg_agent_relay_unit_name }}"
    systemd_unit_restart: "{{ windows_gpg_agent_relay_script.changed }}"
    systemd_unit_activate: true
    systemd_unit_running_check: true
    systemd_unit_running_check_delay: "3"
    systemd_unit_content: >-
      {{
        lookup(
          'ansible.builtin.template',
          windows_gpg_agent_relay_unit_name
        )
      }}

- name: Validate wants symlink existence
  ansible.builtin.stat:
    path: /etc/systemd/system/multi-user.target.wants/{{ windows_gpg_agent_relay_unit_name }}
