- name: Set facts
  ansible.builtin.set_fact:
    fhs_opt_exe_dir_path: /opt/bin
    fhs_opt_provider_dir_path: /opt/{{ ansible_user }}

- name: Create dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
  become: true
  loop:
    - "{{ fhs_opt_exe_dir_path }}"
    - "{{ fhs_opt_provider_dir_path }}"
