- name: Create shortcut
  ansible.builtin.command:
    cmd: >-
      pwsh.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File
      "{{ role_path }}/files/create-shortcut.ps1"
  changed_when: false
