- name: Install
  ansible.builtin.shell: |
    export VOLTA_HOME=$HOME/.volta && export PATH=$VOLTA_HOME/bin:$PATH

    if command -v volta; then
      exit 0
    fi

    if volta --version | grep --quiet {{ volta_version }}; then
      exit 0
    fi

    curl https://get.volta.sh | bash -s -- --version {{ volta_version }}
    echo status=changed
  register: task
  changed_when: '"status=changed" in task.stdout'
  args: { warn: false }

- name: 'sh : Add block to sh_profile_middle'
  blockinfile:
    path: '{{ sh_profile_middle }}'
    insertafter: EOF
    state: present
    marker: '# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}'
    block: |
      export VOLTA_HOME=$HOME/.volta
      export PATH=$VOLTA_HOME/bin:$PATH

- name: 'bash : Completion'
  ansible.builtin.shell: |
    export VOLTA_HOME=$HOME/.volta && export PATH=$VOLTA_HOME/bin:$PATH

    fvolta={{ bash_completions }}/volta.bash

    hash_before=$( ( cat $fvolta || true ) | sha256sum )

    volta completions bash > $fvolta

    hash_after=$( ( cat $fvolta || true ) | sha256sum )

    if [ "$hash_before" != "$hash_after" ]; then echo status=changed; fi
  register: task
  changed_when: '"status=changed" in task.stdout'

- name: 'zsh : Completion'
  ansible.builtin.shell: |
    export VOLTA_HOME=$HOME/.volta && export PATH=$VOLTA_HOME/bin:$PATH

    fvolta={{ zsh_completions }}/_volta

    hash_before=$( ( cat $fvolta || true ) | sha256sum )

    volta completions zsh > $fvolta

    hash_after=$( ( cat $fvolta || true ) | sha256sum )

    if [ "$hash_before" != "$hash_after" ]; then echo status=changed; fi
  register: task
  changed_when: '"status=changed" in task.stdout'

- name: Install and set node@18 as default
  ansible.builtin.shell: |
    export VOLTA_HOME=$HOME/.volta && export PATH=$VOLTA_HOME/bin:$PATH
    volta install node@18
  changed_when: false

- name: Install a few tools
  ansible.builtin.shell: |
    export VOLTA_HOME=$HOME/.volta && export PATH=$VOLTA_HOME/bin:$PATH
    volta install prettier
  changed_when: false
