- name: Set dir path facts
  ansible.builtin.set_fact:
    bash__config_dir_path: "{{ base_dirs_xdg__config_dir_path }}/bash"
    bash__completions_dir_path: "{{ base_dirs_xdg__data_dir_path }}/bash-completion/completions"

- name: Set dir path facts for root
  ansible.builtin.set_fact:
    bash__root_config_dir_path: "{{ base_dirs_xdg__root_config_dir_path }}/bash"
    bash__root_completions_dir_path: "{{ base_dirs_xdg__root_data_dir_path }}/bash-completion/completions"

- name: Set script path facts
  ansible.builtin.set_fact:
    bash__completion_script_path: "{{ base_dirs_xdg__config_dir_path }}/bash_completion"
    bash__profile_script_path: "{{ bash__config_dir_path }}/profile.bash"
    bash__bashrc_top_script_path: "{{ bash__config_dir_path }}/bashrc-top.bash"
    bash__bashrc_script_path: "{{ bash__config_dir_path }}/bashrc.bash"
    bash__aliases_script_path: "{{ bash__config_dir_path }}/aliases.bash"

- name: Set script path facts for root
  ansible.builtin.set_fact:
    bash__root_completion_script_path: "{{ base_dirs_xdg__root_config_dir_path }}/bash_completion"
    bash__root_profile_script_path: "{{ bash__root_config_dir_path }}/profile.bash"
    bash__root_bashrc_top_script_path: "{{ bash__root_config_dir_path }}/bashrc-top.bash"
    bash__root_bashrc_script_path: "{{ bash__root_config_dir_path }}/bashrc.bash"
    bash__root_aliases_script_path: "{{ bash__root_config_dir_path }}/aliases.bash"

- name: Create dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=,o=
  loop:
    - "{{ bash__config_dir_path }}"
    - "{{ bash__completions_dir_path }}"

- name: Create dirs for root
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=,o=
  become: true
  loop:
    - "{{ bash__root_config_dir_path }}"
    - "{{ bash__root_completions_dir_path }}"

- name: Create scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: u=rw,g=,o=
    modification_time: preserve
    access_time: preserve
  loop:
    - "{{ bash__completion_script_path }}"
    - "{{ bash__profile_script_path }}"
    - "{{ bash__bashrc_top_script_path }}"
    - "{{ bash__bashrc_script_path }}"
    - "{{ bash__aliases_script_path }}"

- name: Create scripts for root
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: u=rw,g=,o=
    modification_time: preserve
    access_time: preserve
  become: true
  loop:
    - "{{ bash__root_completion_script_path }}"
    - "{{ bash__root_profile_script_path }}"
    - "{{ bash__root_bashrc_top_script_path }}"
    - "{{ bash__root_bashrc_script_path }}"
    - "{{ bash__root_aliases_script_path }}"

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ shell__bash_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export DOT_BASH_CONFIG_DIR_PATH={{ bash__config_dir_path }}
      export DOT_BASH_COMPLETIONS_DIR_PATH={{ bash__completions_dir_path }}
      export DOT_BASH_COMPLETION_SCRIPT_PATH={{ bash__completion_script_path }}
      export DOT_BASH_PROFILE_SCRIPT_PATH={{ bash__profile_script_path }}
      export DOT_BASH_BASHRC_TOP_SCRIPT_PATH={{ bash__bashrc_top_script_path }}
      export DOT_BASH_BASHRC_SCRIPT_PATH={{ bash__bashrc_script_path }}
      export DOT_BASH_ALIASES_SCRIPT_PATH={{ bash__aliases_script_path }}

- name: Set up environment in Bash for root
  ansible.builtin.blockinfile:
    path: "{{ shell__root_bash_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export DOT_BASH_CONFIG_DIR_PATH={{ bash__root_config_dir_path }}
      export DOT_BASH_COMPLETIONS_DIR_PATH={{ bash__root_completions_dir_path }}
      export DOT_BASH_COMPLETION_SCRIPT_PATH={{ bash__root_completion_script_path }}
      export DOT_BASH_PROFILE_SCRIPT_PATH={{ bash__root_profile_script_path }}
      export DOT_BASH_BASHRC_TOP_SCRIPT_PATH={{ bash__root_bashrc_top_script_path }}
      export DOT_BASH_BASHRC_SCRIPT_PATH={{ bash__root_bashrc_script_path }}
      export DOT_BASH_ALIASES_SCRIPT_PATH={{ bash__root_aliases_script_path }}
  become: true

- name: Set up environment in Fish
  ansible.builtin.blockinfile:
    path: "{{ shell__fish_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      set -x DOT_BASH_CONFIG_DIR_PATH {{ bash__config_dir_path }}
      set -x DOT_BASH_COMPLETIONS_DIR_PATH {{ bash__completions_dir_path }}
      set -x DOT_BASH_COMPLETION_SCRIPT_PATH {{ bash__completion_script_path }}
      set -x DOT_BASH_PROFILE_SCRIPT_PATH {{ bash__profile_script_path }}
      set -x DOT_BASH_BASHRC_TOP_SCRIPT_PATH {{ bash__bashrc_top_script_path }}
      set -x DOT_BASH_BASHRC_SCRIPT_PATH {{ bash__bashrc_script_path }}
      set -x DOT_BASH_ALIASES_SCRIPT_PATH {{ bash__aliases_script_path }}

- name: Set up environment in Fish for root
  ansible.builtin.blockinfile:
    path: "{{ shell__root_fish_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      set -x DOT_BASH_CONFIG_DIR_PATH {{ bash__root_config_dir_path }}
      set -x DOT_BASH_COMPLETIONS_DIR_PATH {{ bash__root_completions_dir_path }}
      set -x DOT_BASH_COMPLETION_SCRIPT_PATH {{ bash__root_completion_script_path }}
      set -x DOT_BASH_PROFILE_SCRIPT_PATH {{ bash__root_profile_script_path }}
      set -x DOT_BASH_BASHRC_TOP_SCRIPT_PATH {{ bash__root_bashrc_top_script_path }}
      set -x DOT_BASH_BASHRC_SCRIPT_PATH {{ bash__root_bashrc_script_path }}
      set -x DOT_BASH_ALIASES_SCRIPT_PATH {{ bash__root_aliases_script_path }}
  become: true

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ shell__zsh_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export DOT_BASH_CONFIG_DIR_PATH={{ bash__config_dir_path }}
      export DOT_BASH_COMPLETIONS_DIR_PATH={{ bash__completions_dir_path }}
      export DOT_BASH_COMPLETION_SCRIPT_PATH={{ bash__completion_script_path }}
      export DOT_BASH_PROFILE_SCRIPT_PATH={{ bash__profile_script_path }}
      export DOT_BASH_BASHRC_TOP_SCRIPT_PATH={{ bash__bashrc_top_script_path }}
      export DOT_BASH_BASHRC_SCRIPT_PATH={{ bash__bashrc_script_path }}
      export DOT_BASH_ALIASES_SCRIPT_PATH={{ bash__aliases_script_path }}

- name: Set up environment in Zsh for root
  ansible.builtin.blockinfile:
    path: "{{ shell__root_zsh_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export DOT_BASH_CONFIG_DIR_PATH={{ bash__root_config_dir_path }}
      export DOT_BASH_COMPLETIONS_DIR_PATH={{ bash__root_completions_dir_path }}
      export DOT_BASH_COMPLETION_SCRIPT_PATH={{ bash__root_completion_script_path }}
      export DOT_BASH_PROFILE_SCRIPT_PATH={{ bash__root_profile_script_path }}
      export DOT_BASH_BASHRC_TOP_SCRIPT_PATH={{ bash__root_bashrc_top_script_path }}
      export DOT_BASH_BASHRC_SCRIPT_PATH={{ bash__root_bashrc_script_path }}
      export DOT_BASH_ALIASES_SCRIPT_PATH={{ bash__root_aliases_script_path }}
  become: true

- name: Delete .bash_profile from home
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.bash_profile
    state: absent

- name: Delete .bash_profile from home for root
  ansible.builtin.file:
    path: /root/.bash_profile
    state: absent
  become: true

- name: Place files in home
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user }}/{{ item }}
    mode: u=rw,g=,o=
    backup: true
  loop:
    - .bashrc
    - .bash_logout

- name: Place files in home for root
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /root/{{ item }}
    mode: u=rw,g=,o=
    backup: true
  become: true
  loop:
    - .bashrc
    - .bash_logout

- name: Render and place files in home
  ansible.builtin.template:
    src: "{{ item }}"
    dest: $HOME/{{ item }}
    mode: u=rw,g=,o=
  loop:
    - .profile

- name: Render and place files in home for root
  ansible.builtin.copy:
    dest: /root/{{ item }}
    mode: u=rw,g=,o=
    content: >-
      {{
        lookup('ansible.builtin.template', item, template_vars={
          'shell__bash_login_script_path': shell__root_bash_login_script_path,
        })
      }}
  become: true
  loop:
    - .profile
