- name: Create dir
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.aws
    state: directory
    mode: u=rwx,g=,o=

- name: Place config
  ansible.builtin.copy:
    src: config
    dest: /home/{{ ansible_user }}/.aws/config
    mode: u=rw,g=,o=
    backup: true
   
- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ shell__bash_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export AWS_PROFILE=trallnag

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ shell__zsh_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export AWS_PROFILE=trallnag
