# ------------------------------------------------------------------------------


- name: Install OS packages
  ansible.builtin.package:
    name:
      - zsh
    state: present
  become: true


# ------------------------------------------------------------------------------


- name: Set facts
  ansible.builtin.set_fact:
    zsh_dynrc: $HOME/.config/zsh/dynrc
    zsh_modules: $HOME/.config/zsh/modules
    zsh_completions: $HOME/.local/share/zsh/completions
    zsh_functions: $HOME/.config/zsh/functions

- name: Set facts
  ansible.builtin.set_fact:
    zsh_zshenv_bottom: "{{ zsh_dynrc }}/zshenv-bottom.zsh"
    
    zsh_zprofile_top: "{{ zsh_dynrc }}/zprofile-top.zsh"
    zsh_zprofile_middle: "{{ zsh_dynrc }}/zprofile-middle.zsh"
    zsh_zprofile_bottom: "{{ zsh_dynrc }}/zprofile-bottom.zsh"
    
    zsh_zshrc_top_interactive: "{{ zsh_dynrc }}/zshrc-top-interactive.zsh"
    zsh_zshrc_top_non_interactive: "{{ zsh_dynrc }}/zshrc-top-non-interactive.zsh"
    zsh_zshrc_middle: "{{ zsh_dynrc }}/zshrc-middle.zsh"
    zsh_zshrc_bottom_before_comp_init: "{{ zsh_dynrc }}/zshrc-bottom-before-comp-init.zsh"
    zsh_zshrc_bottom_after_comp_init: "{{ zsh_dynrc }}/zshrc-bottom-after-comp-init.zsh"
    
    zsh_zlogin_bottom: "{{ zsh_dynrc }}/zlogin-bottom.zsh"
    
    zsh_zlogout_bottom: "{{ zsh_dynrc }}/zlogout-bottom.zsh"


# ------------------------------------------------------------------------------


- name: Create directories
  ansible.builtin.shell: |
    mkdir -p ~/.cache/zsh

    mkdir -p {{ zsh_dynrc }}
    mkdir -p {{ zsh_modules }}
    mkdir -p {{ zsh_completions }}
    mkdir -p {{ zsh_functions }}
  args: {warn: false} 
  changed_when: false

- name: Create rc files
  ansible.builtin.shell: |
    >> {{ zsh_zshenv_bottom }}

    >> {{ zsh_zprofile_top }}
    >> {{ zsh_zprofile_middle }}
    >> {{ zsh_zprofile_bottom }}

    >> {{ zsh_zshrc_top_interactive }}
    >> {{ zsh_zshrc_top_non_interactive }}
    >> {{ zsh_zshrc_middle }}
    >> {{ zsh_zshrc_bottom_before_comp_init }}
    >> {{ zsh_zshrc_bottom_after_comp_init }}

    >> {{ zsh_zlogin_bottom }}
    >> {{ zsh_zlogout_bottom }}
  args: {warn: false} 
  changed_when: false


# ------------------------------------------------------------------------------


- name: RCs
  import_tasks: run-configurations.yaml

- name: Modules
  import_tasks: modules.yaml


# ------------------------------------------------------------------------------
