# ------------------------------------------------------------------------------
# ~/.zshenv


- name: Place ~/.zshenv
  ansible.builtin.shell: |
    echo 'ZDOTDIR=~/.config/zsh' > ~/.zshenv
    echo 'source $ZDOTDIR/.zshenv' >> ~/.zshenv
  args: {warn: false}
  changed_when: false


# ------------------------------------------------------------------------------
# ~/.config/zsh/.zshenv


- name: Place ~/.config/zsh/.zshenv
  ansible.builtin.template:
    src: .zshenv
    dest: ~/.config/zsh/.zshenv
    mode: u=rw,g=r,o=r
    force: true
  register: task

- name: Compile ~/.config/zsh/.zshenv
  when: task.changed
  ansible.builtin.command: zsh -c 'zcompile -R ~/.config/zsh/.zshenv'


# ------------------------------------------------------------------------------
# ~/.config/zsh/.zprofile


- name: Place ~/.config/zsh/.zprofile
  ansible.builtin.template:
    src: .zprofile
    dest: ~/.config/zsh/.zprofile
    mode: u=rw,g=r,o=r
    force: true
  register: task

- name: Compile ~/.config/zsh/.zprofile
  when: task.changed
  ansible.builtin.command: zsh -c 'zcompile -R ~/.config/zsh/.zprofile'


# ------------------------------------------------------------------------------
# ~/.config/zsh/.zshrc


- name: Place ~/.config/zsh/.zshrc
  ansible.builtin.template:
    src: .zshrc
    dest: ~/.config/zsh/.zshrc
    mode: u=rw,g=r,o=r
    force: true
  register: task

- name: Compile ~/.config/zsh/.zshrc
  when: task.changed
  ansible.builtin.command: zsh -c 'zcompile -R ~/.config/zsh/.zshrc'


# ------------------------------------------------------------------------------
# ~/.config/zsh/.zlogin


- name: Place ~/.config/zsh/.zlogin
  ansible.builtin.template:
    src: .zlogin
    dest: ~/.config/zsh/.zlogin
    mode: u=rw,g=r,o=r
    force: true
  register: task

- name: Compile ~/.config/zsh/.zlogin
  when: task.changed
  ansible.builtin.command: zsh -c 'zcompile -R ~/.config/zsh/.zlogin'


# ------------------------------------------------------------------------------
# ~/.config/zsh/.zlogout


- name: Place ~/.config/zsh/.zlogout
  ansible.builtin.template:
    src: .zlogout
    dest: ~/.config/zsh/.zlogout
    mode: u=rw,g=r,o=r
    force: true
  register: task

- name: Compile ~/.config/zsh/.zlogout
  when: task.changed
  ansible.builtin.command: zsh -c 'zcompile -R ~/.config/zsh/.zlogout'


# ------------------------------------------------------------------------------
