- name: Create dir
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.aws
    state: directory
    mode: u=rwx,g=,o=

- name: Place config
  ansible.builtin.copy:
    dest: /home/{{ ansible_user }}/.aws/config
    mode: u=rw,g=,o=
    content: |
      [profile trallnag]
      sso_session = trallnag
      sso_account_id = 617685949322
      sso_role_name = AdministratorAccess
      region = eu-central-1
      output = yaml

      [sso-session trallnag]
      sso_start_url = https://d-9967527590.awsapps.com/start/#
      sso_region = eu-central-1
      sso_registration_scopes = sso:account:access

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ shell__bash_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export AWS_PROFILE=trallnag

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ shell__zsh_login_script_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export AWS_PROFILE=trallnag
