- name: Clone asdf repository to ~/.asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: 'v0.10.2'
    force: true

- name: 'bash : Add init block to {{ bash_bashrc_top }}'
  ansible.builtin.blockinfile:
    path: '{{ bash_bashrc_top }}'
    insertbefore: BOF
    marker: '# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}'
    block: |
      source ~/.asdf/asdf.sh
      source ~/.asdf/completions/asdf.bash

- name: 'zsh : Add init block to {{ zsh_zshrc_top_non_interactive }}'
  ansible.builtin.blockinfile:
    path: '{{ zsh_zshrc_top_non_interactive }}'
    insertbefore: BOF
    marker: '# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}'
    block: |
      source ~/.asdf/asdf.sh
      fpath=($ASDF_DIR/completions $fpath)

- name: Install shfmt
  ansible.builtin.import_role:
    name: trallnag.asdf_plugin
  vars:
    asdf_plugin_name: shfmt
    asdf_plugin_git_url: https://github.com/luizm/asdf-shfmt
    asdf_plugin_package_versions: ['3.5.1']
    asdf_plugin_package_version_global: '3.5.1'

- name: Install shellcheck
  ansible.builtin.import_role:
    name: trallnag.asdf_plugin
  vars:
    asdf_plugin_name: shellcheck
    asdf_plugin_git_url: https://github.com/luizm/asdf-shellcheck
    asdf_plugin_package_versions: ['0.8.0']
    asdf_plugin_package_version_global: '0.8.0'
