- name: Work
  ansible.builtin.command:
    cmd: >-
      pwsh.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File
      "{{ role_path }}/files/work.ps1"
  register: task
  changed_when: "'status=changed' in task.stdout"
